# Generated by Django 5.1.1 on 2024-11-18 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Musicians', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicianmodel',
            name='Phone_number',
            field=models.CharField(max_length=20),
        ),
    ]
