# Generated by Django 5.1.1 on 2024-11-18 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Album', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albummodel',
            name='Rating',
            field=models.IntegerField(choices=[(3, '3'), (5, '5'), (2, '2'), (4, '4'), (1, '1')]),
        ),
    ]
